CLIENT_ERROR_DEFAULT = "Bad input parameters."
UNAUTHORIZED_DEFAULT = "Invalid authentication."
FORBIDDEN_DEFAULT = "Permission denied."
NOT_FOUND_DEFAULT = "Resource not found."
CONFLICT_DEFAULT = "Conflict with existing resource."
INTERNAL_SERVER_ERROR_DEFAULT = "Internal server error."
