"""add_tasks_table

Revision ID: 3b76a118324b
Revises:
Create Date: 2024-06-19 08:48:05.893821

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "3b76a118324b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("status", mysql.TINYINT(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    # ### end Alembic commands ###
